<x-layouts.app title="{{ $instruction->exists ? 'Edit WI' : 'Buat WI' }}">
<section class="section editor-page">
  <div class="section-heading"><div><p class="eyebrow">WI EDITOR</p><h1>{{ $instruction->exists ? 'Edit Work Instruction' : 'Buat Work Instruction' }}</h1></div><a href="{{ route('manage.instructions.index') }}">← Kembali</a></div>
  @if($instruction->status === 'rejected')<div class="notice rejection"><strong>Perlu revisi</strong><br>{{ $instruction->review_notes }}</div>@endif
  <form id="wi-form" method="post" enctype="multipart/form-data" action="{{ $instruction->exists ? route('manage.instructions.update', $instruction) : route('manage.instructions.store') }}">
    @csrf @if($instruction->exists)@method('PUT')@endif
    <div class="form-grid"><label>Judul<input name="title" value="{{ old('title', $instruction->title) }}" required maxlength="180"></label><label>Kategori<select name="category_id" required><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $instruction->category_id) == $category->id)>{{ $category->name }} ({{ strtoupper($category->type) }})</option>@endforeach</select></label></div>
    <label>Ringkasan<textarea name="excerpt" rows="2" maxlength="500">{{ old('excerpt', $instruction->excerpt) }}</textarea></label>
    <label>Lampiran PDF <small>(maksimal 15 MB; hanya dapat dilihat IT/Admin)</small><input type="file" name="attachment_pdf" accept="application/pdf">@error('attachment_pdf')<span class="field-error">{{ $message }}</span>@enderror</label>
    @if($instruction->attachment_path)<p class="metadata">Lampiran saat ini: <a href="{{ route('library.attachment', $instruction) }}" target="_blank" rel="noopener">{{ $instruction->attachment_name }}</a>. Unggah file baru untuk menggantikannya.</p>@endif
    <input type="hidden" id="content_json" name="content_json"><input type="hidden" id="content_html" name="content_html">
    <div class="editor-shell"><div id="editor-toolbar" class="toolbar"><button type="button" data-command="undo">↶</button><button type="button" data-command="redo">↷</button><span></span><button type="button" data-command="bold"><b>B</b></button><button type="button" data-command="italic"><i>I</i></button><button type="button" data-command="underline"><u>U</u></button><button type="button" data-command="bulletList">• List</button><button type="button" data-command="orderedList">1. List</button><button type="button" data-command="heading">H2</button><button type="button" data-command="link">Link</button><button type="button" data-command="image">Gambar</button><button type="button" data-command="table">Tabel</button><button type="button" data-command="divider">—</button></div><div id="editor" data-content='@json($instruction->content_json ?? ["type" => "doc", "content" => []])' data-html='@json($instruction->content_html ?? "")'></div></div>
    <div class="form-actions"><select name="status">@if(auth()->user()->isAdmin())<option value="draft" @selected(old('status', $instruction->status) === 'draft')>Simpan sebagai draft</option><option value="published" @selected(old('status', $instruction->status) === 'published')>Terbitkan langsung</option>@else<option value="draft" @selected(old('status', $instruction->status) === 'draft')>Simpan sebagai draft</option><option value="pending_review" @selected(old('status', $instruction->status) === 'pending_review')>Ajukan untuk review</option>@endif</select><button class="button">Simpan WI</button></div>
  </form>
  @if(auth()->user()->isAdmin() && $instruction->status === 'pending_review')<form class="review-form" method="post" action="{{ route('manage.instructions.review', $instruction) }}">@csrf<h2>Review Admin</h2><label>Catatan review<textarea name="review_notes" rows="3" placeholder="Wajib diisi jika menolak WI"></textarea></label><button class="button" name="decision" value="published">Setujui & terbitkan</button><button class="button button-reject" name="decision" value="rejected">Tolak untuk revisi</button></form>@endif
</section><script type="module" src="{{ asset('js/editor.js') }}"></script></x-layouts.app>
